(
 (.dynlink_internal.objs/native/dynlink_common.cmx as dynlink/dynlink_common.cmx)
    (.dynlink_internal.objs/native/dynlink_platform_intf.cmx as dynlink/dynlink_platform_intf.cmx)
    (.dynlink_internal.objs/native/dynlink_types.cmx as dynlink/dynlink_types.cmx)
    (.dynlink_internal.objs/native/dynlink.cmx as dynlink/dynlink.cmx)
    (dynlink.cma as dynlink/dynlink.cma)
    (dynlink.cmxa as dynlink/dynlink.cmxa)
    (dynlink.a as dynlink/dynlink.a)
;    (dynlink.cmxs as dynlink/dynlink.cmxs)
    (dynlink.mli as dynlink/dynlink.mli)
    (dynlink.cmi as dynlink/dynlink.cmi)
    (.dynlink_internal.objs/byte/dynlink.cmti as dynlink/dynlink.cmti)
    (extract_crc.bc as dynlink/extract_crc)

    .dynlink_compilerlibs.objs/native/dynlink_compilerlibs__Misc.cmx
)
