(
   .dynlink_internal.objs/native/dynlink_common.cmx
    .dynlink_internal.objs/native/dynlink_platform_intf.cmx
    .dynlink_internal.objs/native/dynlink_types.cmx
    .dynlink_internal.objs/native/dynlink.cmx
    dynlink.cma
    dynlink.cmxa
    dynlink.a
;    dynlink.cmxs
    dynlink.mli
    dynlink.cmi
    (.dynlink_internal.objs/byte/dynlink.cmti as dynlink.cmti)
    (extract_crc.bc as extract_crc)

    .dynlink_compilerlibs.objs/native/dynlink_compilerlibs__Misc.cmx
)
