[@@@ocaml.warning "+a-30-40-41-42"]

let add_discriminator dbg file d =
  (* CR-someday gyorsh: discriminators aren't supported yet in debug info
     generated by ocaml compiler. It can be easily added, but for now we use
     line numbers instead, to reduce the number of different compiler changes
     required to make ocamlfdo work. *)
  let pos = { Lexing.dummy_pos with pos_fname = file; pos_lnum = d } in
  let loc = { Location.loc_start = pos; loc_end = pos; loc_ghost = true } in
  let nd = Debuginfo.from_location (Lambda.Loc_known { loc; scopes = [] }) in
  Debuginfo.concat dbg nd

let add t ~file =
  let update (i : _ Cfg.instruction) =
    { i with dbg = add_discriminator i.dbg file i.id }
  in
  let update_block _ (block : Cfg.basic_block) =
    block.terminator <- update block.terminator;
    block.body <- List.map update block.body
  in
  Cfg.iter_blocks t ~f:update_block
