(* TEST
   { native; }
*)
open Nativeint

let test_cases =
  let int_size = Nativeint.size in
  let rng = Random.State.make [| int_size |] in
  (* sparse test cases, concentrated around 0, the limits, and powers of 2 *)
  List.init (int_size - 1) (fun size ->
    let bit = (shift_left one) size in
    let rand () =
      Random.State.nativeint_in_range rng
        ~min:(shift_right_logical bit 1)
        ~max:(pred bit)
    in
    [ bit;
      rand ();
      lognot (rand ());
      (sub max_int) (rand ());
      lognot ((sub max_int) (rand ())) ])
  |> List.concat
  |> List.sort_uniq compare

let[@inline never] check ~dividend ~divisor ~quotient ~remainder =
  assert (divisor <> 0n);
  assert (quotient = div dividend divisor);
  assert (remainder = rem dividend divisor);
  assert (dividend = add (mul quotient divisor) remainder);
  assert
    (if divisor = min_int
     then remainder <> min_int
     else abs remainder < abs divisor);
  let[@inline] sign x = if x < 0n then -1 else if x = 0n then 0 else 1 in
  assert (remainder = 0n || sign remainder = sign dividend)

let[@inline always] [@specialise always] check ~divisor =
  ListLabels.iter test_cases ~f:(fun dividend ->
    (Sys.opaque_identity check)
      ~dividend
      ~divisor
      ~quotient:(div dividend divisor)
      ~remainder:(rem dividend divisor)
  )

(* manual tests *)
let () = check ~divisor:3n
let () = check ~divisor:(-3n)
let () = check ~divisor:65537n
let () = check ~divisor:(-65537n)

(* checks generated by test_cases. These get inlined so the division by a constant is
   replaced *)

let () = check ~divisor:0x1n
let () = check ~divisor:0x2n
let () = check ~divisor:0x4n
let () = check ~divisor:0x7n
let () = check ~divisor:0x8n
let () = check ~divisor:0xdn
let () = check ~divisor:0x10n
let () = check ~divisor:0x15n
let () = check ~divisor:0x20n
let () = check ~divisor:0x2an
let () = check ~divisor:0x40n
let () = check ~divisor:0x4fn
let () = check ~divisor:0x80n
let () = check ~divisor:0xa3n
let () = check ~divisor:0x100n
let () = check ~divisor:0x154n
let () = check ~divisor:0x200n
let () = check ~divisor:0x339n
let () = check ~divisor:0x400n
let () = check ~divisor:0x6cfn
let () = check ~divisor:0x800n
let () = check ~divisor:0x820n
let () = check ~divisor:0x1000n
let () = check ~divisor:0x107an
let () = check ~divisor:0x2000n
let () = check ~divisor:0x3334n
let () = check ~divisor:0x4000n
let () = check ~divisor:0x7b3an
let () = check ~divisor:0x8000n
let () = check ~divisor:0xb205n
let () = check ~divisor:0x10000n
let () = check ~divisor:0x18e6fn
let () = check ~divisor:0x20000n
let () = check ~divisor:0x3efc3n
let () = check ~divisor:0x40000n
let () = check ~divisor:0x429bfn
let () = check ~divisor:0x80000n
let () = check ~divisor:0x8fcaen
let () = check ~divisor:0x100000n
let () = check ~divisor:0x16d760n
let () = check ~divisor:0x200000n
let () = check ~divisor:0x3c068en
let () = check ~divisor:0x400000n
let () = check ~divisor:0x773070n
let () = check ~divisor:0x800000n
let () = check ~divisor:0xf21538n
let () = check ~divisor:0x1000000n
let () = check ~divisor:0x13f99d3n
let () = check ~divisor:0x2000000n
let () = check ~divisor:0x3846a5en
let () = check ~divisor:0x4000000n
let () = check ~divisor:0x5fab3ffn
let () = check ~divisor:0x8000000n
let () = check ~divisor:0xf4a77f8n
let () = check ~divisor:0x10000000n
let () = check ~divisor:0x10fb6962n
let () = check ~divisor:0x20000000n
let () = check ~divisor:0x3bcd549fn
let () = check ~divisor:0x40000000n
let () = check ~divisor:0x4f952039n
let () = check ~divisor:0x80000000n
let () = check ~divisor:0xeebeb75bn
let () = check ~divisor:0x100000000n
let () = check ~divisor:0x18ec33361n
let () = check ~divisor:0x200000000n
let () = check ~divisor:0x3242a7138n
let () = check ~divisor:0x400000000n
let () = check ~divisor:0x6bfbaac2fn
let () = check ~divisor:0x800000000n
let () = check ~divisor:0x8a8c7567dn
let () = check ~divisor:0x1000000000n
let () = check ~divisor:0x1027b086b6n
let () = check ~divisor:0x2000000000n
let () = check ~divisor:0x28474c2119n
let () = check ~divisor:0x4000000000n
let () = check ~divisor:0x7a93d7fe87n
let () = check ~divisor:0x8000000000n
let () = check ~divisor:0xfb4c23c489n
let () = check ~divisor:0x10000000000n
let () = check ~divisor:0x1f89f89e294n
let () = check ~divisor:0x20000000000n
let () = check ~divisor:0x355e3337296n
let () = check ~divisor:0x40000000000n
let () = check ~divisor:0x629bf8bccb0n
let () = check ~divisor:0x80000000000n
let () = check ~divisor:0xbfe906f1b92n
let () = check ~divisor:0x100000000000n
let () = check ~divisor:0x191407f71472n
let () = check ~divisor:0x200000000000n
let () = check ~divisor:0x36b5f12f9313n
let () = check ~divisor:0x400000000000n
let () = check ~divisor:0x5e3f23f0dddan
let () = check ~divisor:0x800000000000n
let () = check ~divisor:0xbef5e282e032n
let () = check ~divisor:0x1000000000000n
let () = check ~divisor:0x18a24ff8561ecn
let () = check ~divisor:0x2000000000000n
let () = check ~divisor:0x2369e32fbc992n
let () = check ~divisor:0x4000000000000n
let () = check ~divisor:0x4ef620f95b74fn
let () = check ~divisor:0x8000000000000n
let () = check ~divisor:0x90411098f476en
let () = check ~divisor:0x10000000000000n
let () = check ~divisor:0x10f1bf16dd463bn
let () = check ~divisor:0x20000000000000n
let () = check ~divisor:0x34a2bdb789e08dn
let () = check ~divisor:0x40000000000000n
let () = check ~divisor:0x5c6e3e4595806en
let () = check ~divisor:0x80000000000000n
let () = check ~divisor:0xac2cb82fecde51n
let () = check ~divisor:0x100000000000000n
let () = check ~divisor:0x120f735945bbc99n
let () = check ~divisor:0x200000000000000n
let () = check ~divisor:0x3039469e51b64a2n
let () = check ~divisor:0x400000000000000n
let () = check ~divisor:0x5a3c0b43e9a2efcn
let () = check ~divisor:0x800000000000000n
let () = check ~divisor:0xe8a22c0435b87b6n
let () = check ~divisor:0x1000000000000000n
let () = check ~divisor:0x1fbb93be9aaf0524n
let () = check ~divisor:0x2000000000000000n
let () = check ~divisor:0x2e9cce8cd5e94a7dn
let () = check ~divisor:0x4000000000000000n
let () = check ~divisor:0x5b14e7c342ea8ea7n
let () = check ~divisor:0x69c59104b185e6c4n
let () = check ~divisor:0x75ef5d214801e93cn
let () = check ~divisor:0x799689af7dbe5446n
let () = check ~divisor:0x7d95c4665cbcb9c3n
let () = check ~divisor:0x7e5e05e4253316b3n
let () = check ~divisor:0x7f3f1cf2a9259909n
let () = check ~divisor:0x7fb8a694f7cfaf74n
let () = check ~divisor:0x7fdef9649771cd3fn
let () = check ~divisor:0x7fe2434086fad31dn
let () = check ~divisor:0x7ff605bc4d7fe111n
let () = check ~divisor:0x7ffa5eac37685893n
let () = check ~divisor:0x7ffd535d13bd148bn
let () = check ~divisor:0x7ffe0695587e72cfn
let () = check ~divisor:0x7fff5a52b5d17bccn
let () = check ~divisor:0x7fff997b597c31a9n
let () = check ~divisor:0x7fffd087a97e11cbn
let () = check ~divisor:0x7fffec0450d9ef2cn
let () = check ~divisor:0x7ffff778cb53dfd0n
let () = check ~divisor:0x7ffffacb58cdaf74n
let () = check ~divisor:0x7ffffc3dcdbe97c7n
let () = check ~divisor:0x7ffffebc41ebb444n
let () = check ~divisor:0x7fffff613dc9052en
let () = check ~divisor:0x7fffff80ce85747cn
let () = check ~divisor:0x7fffffd022afc735n
let () = check ~divisor:0x7fffffe1cb8677ben
let () = check ~divisor:0x7ffffff7b4e38518n
let () = check ~divisor:0x7ffffff968923187n
let () = check ~divisor:0x7ffffffd2da09b66n
let () = check ~divisor:0x7ffffffee3a78db9n
let () = check ~divisor:0x7fffffff073a7723n
let () = check ~divisor:0x7fffffffb13e2009n
let () = check ~divisor:0x7fffffffd91672b1n
let () = check ~divisor:0x7fffffffef5ddd1en
let () = check ~divisor:0x7ffffffff0b85de5n
let () = check ~divisor:0x7ffffffffa24db09n
let () = check ~divisor:0x7ffffffffc646ef8n
let () = check ~divisor:0x7ffffffffee78250n
let () = check ~divisor:0x7fffffffff2a9595n
let () = check ~divisor:0x7fffffffff899f3an
let () = check ~divisor:0x7fffffffffd826b9n
let () = check ~divisor:0x7fffffffffe87226n
let () = check ~divisor:0x7ffffffffff75f7dn
let () = check ~divisor:0x7ffffffffff8229an
let () = check ~divisor:0x7ffffffffffc5874n
let () = check ~divisor:0x7ffffffffffe7639n
let () = check ~divisor:0x7fffffffffff1ec4n
let () = check ~divisor:0x7fffffffffff96e7n
let () = check ~divisor:0x7fffffffffffd43cn
let () = check ~divisor:0x7fffffffffffecf1n
let () = check ~divisor:0x7ffffffffffff4a2n
let () = check ~divisor:0x7ffffffffffffae8n
let () = check ~divisor:0x7ffffffffffffd12n
let () = check ~divisor:0x7ffffffffffffe26n
let () = check ~divisor:0x7fffffffffffff11n
let () = check ~divisor:0x7fffffffffffffa7n
let () = check ~divisor:0x7fffffffffffffc7n
let () = check ~divisor:0x7fffffffffffffe3n
let () = check ~divisor:0x7ffffffffffffff4n
let () = check ~divisor:0x7ffffffffffffff8n
let () = check ~divisor:0x7ffffffffffffffdn
let () = check ~divisor:0x7ffffffffffffffen
let () = check ~divisor:0x7fffffffffffffffn
let () = check ~divisor:0x8000000000000000n
let () = check ~divisor:0x8000000000000001n
let () = check ~divisor:0x8000000000000002n
let () = check ~divisor:0x8000000000000005n
let () = check ~divisor:0x800000000000000dn
let () = check ~divisor:0x8000000000000017n
let () = check ~divisor:0x8000000000000028n
let () = check ~divisor:0x800000000000005an
let () = check ~divisor:0x80000000000000e2n
let () = check ~divisor:0x80000000000001e3n
let () = check ~divisor:0x80000000000002dbn
let () = check ~divisor:0x80000000000006efn
let () = check ~divisor:0x80000000000009e2n
let () = check ~divisor:0x80000000000010dan
let () = check ~divisor:0x80000000000025c6n
let () = check ~divisor:0x8000000000006a1dn
let () = check ~divisor:0x8000000000009f0fn
let () = check ~divisor:0x80000000000192d8n
let () = check ~divisor:0x8000000000026c30n
let () = check ~divisor:0x80000000000497d7n
let () = check ~divisor:0x80000000000d9189n
let () = check ~divisor:0x8000000000114ec3n
let () = check ~divisor:0x8000000000305e32n
let () = check ~divisor:0x8000000000405a0fn
let () = check ~divisor:0x8000000000a3b89an
let () = check ~divisor:0x8000000001416aacn
let () = check ~divisor:0x800000000236f72dn
let () = check ~divisor:0x80000000041e824fn
let () = check ~divisor:0x800000000ace82edn
let () = check ~divisor:0x800000001baeef0cn
let () = check ~divisor:0x800000002f370abfn
let () = check ~divisor:0x800000006f4eea4an
let () = check ~divisor:0x80000000ee73e06cn
let () = check ~divisor:0x8000000163ff75cdn
let () = check ~divisor:0x80000002c054c81fn
let () = check ~divisor:0x800000052e7d2f21n
let () = check ~divisor:0x8000000d8a7e1bacn
let () = check ~divisor:0x800000103dd26b53n
let () = check ~divisor:0x800000223a470101n
let () = check ~divisor:0x8000007fa4045f80n
let () = check ~divisor:0x800000e45d6fd0den
let () = check ~divisor:0x800001e78d8346d6n
let () = check ~divisor:0x8000029b1675a7a8n
let () = check ~divisor:0x8000053849ced170n
let () = check ~divisor:0x80000c68934248b4n
let () = check ~divisor:0x800015b93f5ea575n
let () = check ~divisor:0x8000222ac6abfce3n
let () = check ~divisor:0x800071767fcd2050n
let () = check ~divisor:0x8000dc7d0d078691n
let () = check ~divisor:0x8001c6d218244d58n
let () = check ~divisor:0x8002c17faae76758n
let () = check ~divisor:0x80067449a16e79d1n
let () = check ~divisor:0x80095c91235e8715n
let () = check ~divisor:0x8014ad09556ad699n
let () = check ~divisor:0x8038d558ee7f2b82n
let () = check ~divisor:0x8068ba2ea24e6b16n
let () = check ~divisor:0x80d635ef2e7f90d8n
let () = check ~divisor:0x813b4c28ac280801n
let () = check ~divisor:0x820afdd334b1649en
let () = check ~divisor:0x87cfe1f0910cc176n
let () = check ~divisor:0x8ba913d5cdea6590n
let () = check ~divisor:0x9587999411c567ben
let () = check ~divisor:0xb5f5db077018f8c8n
let () = check ~divisor:0xcfe662f0c82e6584n
let () = check ~divisor:0xe98376a7e310494an
let () = check ~divisor:0xf52637e14e4cd80en
let () = check ~divisor:0xf92a69c1da392d64n
let () = check ~divisor:0xfdf40e66c7956c47n
let () = check ~divisor:0xfea5fcdd8582c81bn
let () = check ~divisor:0xff2ef1ffe1d2a282n
let () = check ~divisor:0xffa815c4429b0c98n
let () = check ~divisor:0xffc45909b9012c9en
let () = check ~divisor:0xffe8e9a5fce64df8n
let () = check ~divisor:0xfff08241e22d092en
let () = check ~divisor:0xfffad56035621e99n
let () = check ~divisor:0xfffd47754fafaf91n
let () = check ~divisor:0xfffe719238e7a731n
let () = check ~divisor:0xffff47f0f40dd886n
let () = check ~divisor:0xffff9ab441ef092en
let () = check ~divisor:0xffffdf57b79f098cn
let () = check ~divisor:0xffffead156a3e7c1n
let () = check ~divisor:0xfffff5e3c70abdc8n
let () = check ~divisor:0xfffff866180fd19cn
let () = check ~divisor:0xfffffd5287159496n
let () = check ~divisor:0xfffffecf8400bd7en
let () = check ~divisor:0xffffff6d01927255n
let () = check ~divisor:0xffffff81fbc885b5n
let () = check ~divisor:0xffffffcf41c5afd0n
let () = check ~divisor:0xffffffe17bb98621n
let () = check ~divisor:0xfffffff6cdf34b1bn
let () = check ~divisor:0xfffffffb55ba25d3n
let () = check ~divisor:0xfffffffde54a6ad8n
let () = check ~divisor:0xfffffffe3f4de45fn
let () = check ~divisor:0xffffffff11069f3bn
let () = check ~divisor:0xffffffffba8fb1dcn
let () = check ~divisor:0xffffffffd78c6873n
let () = check ~divisor:0xffffffffe8de94f9n
let () = check ~divisor:0xfffffffff66a8bdbn
let () = check ~divisor:0xfffffffff8658c5dn
let () = check ~divisor:0xfffffffffd6cf681n
let () = check ~divisor:0xfffffffffeb11b5an
let () = check ~divisor:0xffffffffff59ed0cn
let () = check ~divisor:0xffffffffff992755n
let () = check ~divisor:0xffffffffffc31c58n
let () = check ~divisor:0xffffffffffedb322n
let () = check ~divisor:0xfffffffffff484f2n
let () = check ~divisor:0xfffffffffff8208fn
let () = check ~divisor:0xfffffffffffcdaa9n
let () = check ~divisor:0xfffffffffffe7764n
let () = check ~divisor:0xffffffffffff7710n
let () = check ~divisor:0xffffffffffffa7abn
let () = check ~divisor:0xffffffffffffd4f3n
let () = check ~divisor:0xffffffffffffe767n
let () = check ~divisor:0xfffffffffffff299n
let () = check ~divisor:0xfffffffffffffb81n
let () = check ~divisor:0xfffffffffffffc92n
let () = check ~divisor:0xfffffffffffffeaan
let () = check ~divisor:0xffffffffffffff40n
let () = check ~divisor:0xffffffffffffffb6n
let () = check ~divisor:0xffffffffffffffd1n
let () = check ~divisor:0xffffffffffffffe2n
let () = check ~divisor:0xfffffffffffffff4n
let () = check ~divisor:0xfffffffffffffff8n
let () = check ~divisor:0xfffffffffffffffcn
let () = check ~divisor:0xfffffffffffffffen
let () = check ~divisor:0xffffffffffffffffn
