/* This file is generated by tools/gen_sizeclasses.ml */
#define POOL_WSIZE 16384
#define POOL_HEADER_WSIZE 4
#define SIZECLASS_MAX 128
#define NUM_SIZECLASSES 30
static const unsigned int wsize_sizeclass[NUM_SIZECLASSES] =
{ 1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 14, 16, 17, 19, 22, 25, 28, 32, 36, 41, 46,
  52, 58, 65, 73, 82, 92, 103, 115, 128 };
static const unsigned char wastage_sizeclass[NUM_SIZECLASSES] =
{ 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 12, 9, 2, 12, 5, 0, 28, 0, 21, 4, 0, 24,
  0, 28, 62, 4, 3, 50, 124 };
static const unsigned char sizeclass_wsize[SIZECLASS_MAX + 1] =
{ 255, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 13, 13, 14,
  14, 14, 15, 15, 15, 16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19,
  19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22,
  23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25,
  25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27,
  27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,
  29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29 };
