name: 80ch
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  build:
    if: ${{ ! contains( github.event.pull_request.labels.*.name, 'skip 80ch') }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        ocaml-compiler:
          - "4.14.0"

    steps:
    - name: Checkout the OxCaml repo
      uses: actions/checkout@master

    - name: Checkout the parent branch
      run: git fetch origin HEAD --deepen 1

    - name: Setup OCaml ${{ matrix.ocaml-compiler }}
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - name: Install a recent version of re
      run: opam install 're>=1.10.0'

    - name: Install ocamlformat 0.24.1
      run: opam pin -y ocamlformat 0.24.1

    - name: Check for new >80 character lines
      run: opam exec -- bash .github/workflows/80ch.sh
